package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'IMODCollector_X64Release'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("IMODCollector_X64Release")) {
    dependencies {
        remove(AbsoluteId("MSWMOD_MetaSWAP_MetaSWAPBuildWin64trunk")) {
            artifacts {
                buildRule = tag("release_2410")
                cleanDestination = true
                artifactRules = "MetaSWAP.zip!/x64/Release => metaswap"
            }
        }

        add(AbsoluteId("MSWMOD_MetaSWAP_MetaSWAPBuildWin64_vs")) {
            artifacts {
                buildRule = tag("release_2410")
                cleanDestination = true
                artifactRules = "MetaSWAP.zip!/x64/Release => metaswap"
            }
        }

    }
}
