package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'IMODCollector_X64development'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("IMODCollector_X64development")) {
    dependencies {
        add(AbsoluteId("MSWMOD_MetaSWAP_MetaSWAPDevelopWin64test")) {
            artifacts {
                buildRule = lastSuccessful()
                cleanDestination = true
                artifactRules = "MetaSWAP.zip => metaswap"
                enabled = false
            }
        }

    }
}
