package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'IMODCollector_X64developmentLnx64'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("IMODCollector_X64developmentLnx64")) {
    expectSteps {
        script {
            name = "Create executable with pyinstaller"
            id = "RUNNER_301"
            scriptContent = """
                #!/bin/bash
                module load pixi
                rm -rf dist
                pixi run -e dev install-minimal
                pixi run -e dev pyinstaller --onefile imod_coupler/__main__.py --name imodc
            """.trimIndent()
        }
        script {
            name = "Get version from imod coupler"
            id = "RUNNER_1232"
            scriptContent = "./dist/imodc/imodc --version"
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            id = "RUNNER_301"
            clearConditions()
            workingDir = "coupler"
        }
    }
}
