package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'IMODCollector_X64developmentLnx64'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("IMODCollector_X64developmentLnx64")) {
    dependencies {
        remove(AbsoluteId("Ribasim_Windows_BuildRibasim")) {
            artifacts {
                id = "ARTIFACT_DEPENDENCY_285"
                buildRule = lastSuccessful()
                artifactRules = "libribasim.zip!** => ribasim"
                enabled = false
            }
        }

        add(AbsoluteId("Ribasim_Linux_BuildRibasim")) {
            artifacts {
                id = "ARTIFACT_DEPENDENCY_285"
                buildRule = lastSuccessful()
                artifactRules = "libribasim.zip!** => ribasim"
                enabled = false
            }
        }

    }
}
