package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.script
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'IMODCollector_X64developmentLnx64'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("IMODCollector_X64developmentLnx64")) {
    check(artifactRules == """
        dist/imodc/ => imod_collector.zip!/imod_coupler/
        modflow6/ => imod_collector.zip!/modflow6/
        metaswap/ => imod_collector.zip!/metaswap/
    """.trimIndent()) {
        "Unexpected option value: artifactRules = $artifactRules"
    }
    artifactRules = """
        coupler/dist/imodc/ => imod_collector.zip!/imod_coupler/
        modflow6/ => imod_collector.zip!/modflow6/
        metaswap/ => imod_collector.zip!/metaswap/
    """.trimIndent()

    expectSteps {
        script {
            name = "Create executable with pyinstaller"
            id = "RUNNER_301"
            scriptContent = """
                #!/bin/bash
                module load pixi
                rm -rf dist
                pixi run -e dev install-minimal
                pixi run -e dev pyinstaller --onefile imod_coupler/__main__.py --name imodc
            """.trimIndent()
        }
        script {
            name = "Get version from imod coupler"
            id = "RUNNER_1232"
            scriptContent = "./dist/imodc/imodc --version"
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            id = "RUNNER_301"
            clearConditions()
            workingDir = "coupler"
        }
        update<ScriptBuildStep>(1) {
            id = "RUNNER_1232"
            clearConditions()
            scriptContent = "./coupler/dist/imodc --version"
        }
    }
}
