package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'IMODCollector_X64development'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("IMODCollector_X64development")) {
    dependencies {
        expect(AbsoluteId("MSWMOD_MetaSWAP_MetaSWAPBuildWin64trunk")) {
            snapshot {
            }

            artifacts {
                cleanDestination = true
                artifactRules = "MetaSWAP.zip!/x64/Release => metaswap"
            }
        }
        update(AbsoluteId("MSWMOD_MetaSWAP_MetaSWAPBuildWin64trunk")) {
            snapshot {
            }

            artifacts {
                buildRule = lastSuccessful()
                artifactRules = "MetaSWAP.zip!/x64/Release => metaswap"
            }
        }

        add(AbsoluteId("MSWMOD_MetaSWAP_MetaSWAPDevelopWin64test")) {
            artifacts {
                buildRule = lastSuccessful()
                cleanDestination = true
                artifactRules = "MetaSWAP.zip!/x64/Release => metaswap"
            }
        }

    }
}
