package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'ImodCouplerSandbox'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("ImodCouplerSandbox")
    name = "imod_coupler_sandbox"
    url = "https://github.com/Deltares/imod_coupler"
    branch = "sandbox"
}))

